---
development:
  cloud_name: dw8sniwdq
  api_key: '667473494284631'
  api_secret: SA3qzZ8F1KURbGRmnJQfg-gq6u8
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dw8sniwdq
  api_key: '667473494284631'
  api_secret: SA3qzZ8F1KURbGRmnJQfg-gq6u8
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dw8sniwdq
  api_key: '667473494284631'
  api_secret: SA3qzZ8F1KURbGRmnJQfg-gq6u8
  enhance_image_tag: true
  static_image_support: false
