# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8cbda223e94884468f871553751eb170f51a65a8f9065a7c3bc0b523bc7c113bc2d5cb86a393711884a99dd4f94936c10ec56d20b8455cb2b32f798274ebf9c5

test:
  secret_key_base: e6a19480ad0663358114ad0460b2e6938c8f05943bcea9fd65b9418d5b6d61971c533385da0a80e11ebf908cf6870f6a02fa2cb8c0dcd84b63193238e498ef61

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
